apiVersion: apps/v1
kind: Deployment
metadata:
  name: dz-nats-producer
  namespace: default
  labels:
    app: dz-nats-producer
spec:
  replicas: 0
  selector:
    matchLabels:
      app: dz-nats-producer
  template:
    metadata:
      labels:
        app: dz-nats-producer
    spec:
      containers:
        - name: nats-test
          image: thedavidzhao/nats-test:6
          env:
            - name: NATS_TEST_CONFIG
              value: |
                num_shards: 50
                use_pooling: false
                producers_per_room: 1
                consumers_per_room: 5
                message_rate: 10
                nats:
                  url: nats://nats.default.svc.cluster.local:4222
                logging:
                  json: true
          resources: {}
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 120
      dnsPolicy: ClusterFirst
      imagePullSecrets:
        - name: dockerhub
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - dz-nats-producer
                      - dz-nats-consumer
              topologyKey: kubernetes.io/hostname
            - labelSelector:
                matchExpressions:
                  - key: app.kubernetes.io/name
                    operator: In
                    values:
                      - nats
              topologyKey: kubernetes.io/hostname
